### ISSUE TITLE
Theme demo page has no content

### ISSUE THREAD

**Issue by Psypher9** [jsnjack/hugo-changelog-theme#11]
Hello,

I am trying to make a site with this theme and I just noticed that the [Demo Page](https://themes.gohugo.io/theme/hugo-changelog-theme/) has no content. Is everything working alright?

**Comment by jsnjack** [comment]
Everything should be fine. There is a commit that addresses the issue with the demo page https://github.com/jsnjack/hugo-changelog-theme/commit/b94a13bde2272739893ae528a9f0831592b00096

**Comment by Psypher9** [comment]
Okay, so a release is on the way to update it? Or perhaps there just isn't any seeded content to see, because the demo page is still blank.

**Comment by jsnjack** [comment]
It is up to hugo team to update a pointer to the new version of the theme. I think they are going to do it in the next few days. You can clone the repo and run demo website locally

**Comment by Psypher9** [comment]
Ah I see! Thank you for clarifying.
