### ISSUE TITLE
Deprecated features are cut off

### ISSUE THREAD

**Issue by tomkerkhove** [jsnjack/hugo-changelog-theme#18]
Deprecated features are cut off when the list is too long, example: https://changelog.promitor.io/

**Comment by jsnjack** [comment]
Thank you for reporting the issue @tomkerkhove . The default max-height value was 50 rem (from css framework). It was increased to 100 rem. Should be enough :) You can also modify it yourself by providing custom css styles

**Comment by tomkerkhove** [comment]
Thanks for letting me know!
