### ISSUE TITLE
Add recursive clone instructions to README

### ISSUE THREAD

**Issue by zwbetz-gh** [jsnjack/hugo-changelog-theme#2]
For the original issue and the full discussion, see https://discourse.gohugo.io/t/changelog-theme-scss-error/15917/2

In a nutshell, the README doesn't instruct users to clone the theme recursively. So, if users do a plain `git clone`, then they receive an error.

Please add the relevant instructions to the README.

**Comment by 6J7KZg2f** [comment]
That post, combined with others regarding other themes tipping me off that I needed to install Hugo Extended, were required to get this theme running for me. As a first-day Hugo beginner, this was (as compared to docuapi) a very frustrating theme.
