### ISSUE TITLE
Mixed Content in the Changelog theme demo on the Hugo website 

### ISSUE THREAD

**Issue by onedrawingperday** [jsnjack/hugo-changelog-theme#7]
Hello @jsnjack   I am one of the maintainers of the Hugo Themes repository.

Your theme's demo causes a  [Mixed Content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) browser warning on the Hugo website because in [line 4](https://github.com/jsnjack/hugo-changelog-theme/blob/95a97426c06250fd4e58aae5a303b02e699a08e7/layouts/partials/head.html#L4) of `/layouts/partials/head.html` there is a reference to an insecure URL. The Hugo website is served under `HTTPS`.

To fix this warning either change to `<link href="https://gmpg.org/xfn/11" rel="profile">` or delete it, if it's no longer needed.

Once you do the above please let me know.

Thanks

**Comment by jsnjack** [comment]
Hi @onedrawingperday ! Thank you for reporting it! I have just removed the link
